name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        flutter_channel: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install CMake and Ninja
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y cmake ninja-build
      
      - name: Install GTK and pkg-config (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libgtk-3-dev pkg-config
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.4'

      - name: Install dependencies
        run: flutter pub get
        working-directory: app

      - name: Build Android
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk
        working-directory: app

      - name: Upload Android Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk